global:
  resolve_timeout: 5m

route:
  receiver: "default"

receivers:
  - name: "default"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/SEU-WEBHOOK-SLACK"
        channel: "#alertas-dev"
