name: Deploy to AWS

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_APP: clinica_estetica_api
  ECS_CLUSTER: clinica_estetica_api
  ECS_SERVICE: clinica_estetica_api
  CONTAINER_NAME_APP: clinica_estetica_api

jobs:
  deploy_production:
    if: ${{inputs.branch == 'main' }}
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Construir e enviar a imagem Docker
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)

          docker build -t $ECR_REPOSITORY_APP:$IMAGE_TAG -f .docker/Dockerfile.prod .
          docker tag $ECR_REPOSITORY_APP:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_APP:$IMAGE_TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_APP:$IMAGE_TAG

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Atualizar serviço no ECS
        run: |
          # Obter a definição de tarefa atual
          TASK_DEFINITION=$(aws ecs describe-services \
            --cluster $ECS_CLUSTER \
            --services $ECS_SERVICE \
            --query "services[0].taskDefinition" \
            --output text)

          # Obter os container definitions
          CONTAINER_DEFINITIONS=$(aws ecs describe-task-definition \
            --task-definition $TASK_DEFINITION \
            --query "taskDefinition.containerDefinitions" \
            --output json)

          # Substituir imagem no container definitions
          UPDATED_DEFINITIONS=$(echo "$CONTAINER_DEFINITIONS" | jq \
            --arg IMAGE "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_APP:$IMAGE_TAG" \
            'map(if .name == env.CONTAINER_NAME_APP then .image = $IMAGE else . end)')

          # Registrar nova definição de tarefa
          NEW_TASK_REVISION=$(aws ecs register-task-definition \
            --family $ECS_SERVICE \
            --container-definitions "$UPDATED_DEFINITIONS" \
            --execution-role-arn $(aws ecs describe-task-definition --task-definition $TASK_DEFINITION --query "taskDefinition.executionRoleArn" --output text) \
            --network-mode $(aws ecs describe-task-definition --task-definition $TASK_DEFINITION --query "taskDefinition.networkMode" --output text) \
            --requires-compatibilities $(aws ecs describe-task-definition --task-definition $TASK_DEFINITION --query "taskDefinition.requiresCompatibilities[]" --output text) \
            --cpu $(aws ecs describe-task-definition --task-definition $TASK_DEFINITION --query "taskDefinition.cpu" --output text) \
            --memory $(aws ecs describe-task-definition --task-definition $TASK_DEFINITION --query "taskDefinition.memory" --output text) \
            --query "taskDefinition.revision" --output text)

          # Atualizar o serviço com nova task
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --task-definition $ECS_SERVICE:$NEW_TASK_REVISION \
            --force-new-deployment
