name: Laravel CI

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  # =========================
  # Job 1: Tests + Coverage
  # =========================
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        php: [8.2, 8.3]
        mysql: [5.7, 8.0, 8.1]
        include:
          - php: 8.3
            mysql: 8.0
            os: ubuntu-24.04
            
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ROOT_PASSWORD: root # Senha do root aqui
          MYSQL_DATABASE: clinida_estetica_testing # Nome do banco de dados
        ports:
          - 3306:3306 # Expõe a porta 3306 do container
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      XDEBUG_MODE: coverage
      DB_CONNECTION: mysql_testing
      CI_DB_CONNECTION: mysql_testing
      CI_DB_HOST: 127.0.0.1
      CI_DB_PORT: 3306
      CI_DB_DATABASE: clinida_estetica_testing
      CI_DB_USERNAME: root
      CI_DB_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Validate syntax
        run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo, pdo_mysql, xdebug
          coverage: pcov
          
      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest
          composer dump-autoload
          
      - name: Install PHPStan (if missing)
        run: composer require --dev phpstan/phpstan --no-interaction

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
          
      - name: Prepare environment files
        run: |
          cp .env.testing.pipeline .env.testing
          cp .env.testing.pipeline .env
      
      - name: Clear Laravel caches
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear
          rm -rf bootstrap/cache/*.php

      - name: Generate application key
        run: php artisan key:generate --env=testing
        
      - name: Generate Passport keys
        run: php artisan passport:keys --force

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysql -h $CI_DB_HOST -P $CI_DB_PORT -u$CI_DB_USERNAME -p$CI_DB_PASSWORD -e "SELECT 1;" > /dev/null 2>&1; then
              echo "MySQL is ready!"
              break
            else
              echo "Waiting for MySQL... Attempt $i"
              sleep 5
            fi
          done
          
      - name: Test MySQL connection
        run: mysql -h $CI_DB_HOST -P $CI_DB_PORT -u$CI_DB_USERNAME -p$CI_DB_PASSWORD -e "SHOW DATABASES;"

      - name: Run migrations for testing
        run: php artisan migrate:fresh --database=mysql_testing --env=testing --force
        
      #- name: Run tests with coverage
      #  run: |
      #    mkdir -p coverage
      #    php artisan test --env=testing --stop-on-failure --coverage-html coverage/ --log-junit junit/results.xml
      - name: Run PHPUnit tests with coverage
        run: |
          mkdir -p coverage
          mkdir -p coverage/text
          mkdir -p coverage/html
          mkdir -p coverage/xml
          XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration phpunit.xml
            
      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports-${{ matrix.os }}-${{ matrix.php }}-${{ matrix.mysql }}
          path: | 
            storage/logs/laravel.log
            coverage/
            junit/results.xml
          if-no-files-found: warn
          
      - name: Call Deploy workflow
        uses: ./.github/workflows/deploy.yml
        with:
          env: ${{ inputs.env }}
