name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4 # Ajuste para a versão que seu projeto suporta
          extensions: mbstring, pdo, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test
